services:
  super-easy-file-backups-tests:
    extends:
      file: docker-compose.yml
      service: super-easy-file-backups
    restart: "no"
    environment:
      - START_COMMAND=test
    volumes:
      - ./tests/logs:/app/logs

      - ./tests/projects/test-project:/app/projects/test-project:ro
      - ./tests/projects/single-project:/app/projects/single-project:ro

      - ./tests/backups/test-project:/app/backups/test-project
      - ./tests/backups/single-project:/app/backups/single-project
