name: Docker-compose Tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ./docker-compose.ci.yml
          up-flags: "--build"
