name: Docker compose Tests

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker compose -f docker-compose-tests.yml up --build --exit-code-from super-easy-file-backups-tests
